function change(alcaldia, colonia) {
  alcaldia = document.getElementById(alcaldia);
  colonia = document.getElementById(colonia);
  colonia.value = "";
  colonia.innerHTML = "";

  if (alcaldia.value == "Antioquia") {
    var optionArray = ["|", "Abejorral|Abejorral",
      "Abriaqui|Abriaqui",
      "Amaga|Amaga",
      "Apartado|Apartado",
      "Barbosa|Barbosa",
      "Bello|Bello",
      "Carmen De Viboral|Carmen De Viboral",
      "Envigado|Envigado",
      "Fredonia|Fredonia",
      "Girardota|Girardota",
      "Gomez Plata|Gomez Plata",
      "Guarne|Guarne",
      "Itagui|Itagui",
      "La Estrella|La Estrella",
      "Medellin|Medellin",
      "Sabaneta|Sabaneta",
      "Santa Rosa De Osos|Santa Rosa De Osos"];

  } else if (alcaldia.value == "Atlantico") {
    var optionArray = ["|",
      "Barranquilla|Barranquilla"];

  } else if (alcaldia.value == "Bogota D.C") {
    var optionArray = ["|",
      "Bogota|Bogota"];

  } else if (alcaldia.value == "Bolivar") {
    var optionArray = ["|",
      "Cartagena|Cartagena"];

  } else if (alcaldia.value == "Cesar") {
    var optionArray = ["|",
      "Valledupar|Valledupar"];

  } else if (alcaldia.value == "Cordoba") {
    var optionArray = ["|",
      "Monteria|Monteria"];


  } else if (alcaldia.value == "Cundinamarca") {
    var optionArray = ["|",
      "Cajica|Cajica",
      "Fusagasuga|Fusagasuga"];

  } else if (alcaldia.value == "Huila") {
    var optionArray = ["|",
      "Neiva|Neiva"];

  } else if (alcaldia.value == "Meta") {
    var optionArray = ["|",
       "Acacias|Acacias"];
  };



  for (option = 0; option < optionArray.length; option++) {
    var pair = optionArray[option].split("|");
    var newOption = document.createElement("option");
    newOption.value = pair[0];
    newOption.innerHTML = pair[1];
    colonia.options.add(newOption);
  };

}

function change2(colonia, letra) {

  colonia = document.getElementById(colonia);
  letra = document.getElementById(letra);
  letra.value = "";
  letra.innerHTML = "";


  if (colonia.value == "Abejorral") {
    var optionArray = ["|",
      "Campoalegre|Campoalegre",
      "Chaguala|Chaguala",
      "La Pena|La Pena",
      "Morro Sucio|Morro Sucio",
      "San Bartolo|San Bartolo",
      "Santana|Santana",
      "Santana2|Santana2"];

  } else if (colonia.value == "Abriaqui") {
    var optionArray = ["|",
      "Asdasd|Asdasd",
      "El Trincho|El Trincho",
      "La Cueva|La Cueva",
      "La Porra|La Porra",
      "La Selva|La Selva",
      "Las Brisas|Las Brisas",
      "Los Naranjos|Los Naranjos",
      "Los Pomos|Los Pomos"];

  } else if (colonia.value == "Amaga") {
    var optionArray = ["|",
      "Nuevo Barrio|Nuevo Barrio"];

  } else if (colonia.value == "Apartado") {
    var optionArray = ["|",
      "Nuevo Barrio|Nuevo Barrio"];

  } else if (colonia.value == "Barbosa") {
    var optionArray = ["|",
      "Calle Del Comercio|Calle Del Comercio",
      "La Herradura|La Herradura",
      "Pepe Sierra|Pepe Sierra"];

  } else if (colonia.value == "Bello") {
    var optionArray = ["|",
      "Cabañitas|Cabañitas",
      "Niquia|Niquia",
      "Primavera|Primavera",
      "Santa Ana|Santa Ana"];

  } else if (colonia.value == "Carmen De Viboral") {
    var optionArray = ["|",
      "Carmen|Carmen"];

  } else if (colonia.value == "Envigado") {
    var optionArray = ["|",
      "Abadia|Abadia",
      "Alcalá|Alcalá",
      "Aldea San Lucas|Aldea San Lucas",
      "Alto De Las Flores|Alto De Las Flores",
      "Alto De Misael|Alto De Misael",
      "Andalucia|Andalucia",
      "Bandera Roja|Bandera Roja",
      "Barrio Mesa|Barrio Mesa",
      "Bosques De Zuñiga|Bosques De Zuñiga",
      "Bucarest|Bucarest",
      "Calle Basura|Calle Basura",
      "Camino Verde|Camino Verde",
      "Canalización|Canalización",
      "Cervantes|Cervantes",
      "Chingui|Chingui",
      "Clinica La Policia|Clinica La Policia",
      "Cumbres|Cumbres",
      "El Chinguí|El Chinguí",
      "El Chocho|El Chocho",
      "El Consuelo|El Consuelo",
      "El Dorado|El Dorado",
      "El Embrujo|El Embrujo",
      "El Esmeraldal|El Esmeraldal",
      "El Farolito|El Farolito",
      "El Oasis|El Oasis",
      "El Portal|El Portal",
      "El Salado|El Salado",
      "El Trianón|El Trianón",
      "Envigado|Envigado",
      "Envigado Centro|Envigado Centro",
      "Escobero|Escobero",
      "Esmeraldal|Esmeraldal",
      "Florida|Florida",
      "Gascuña|Gascuña",
      "Guadalcanal|Guadalcanal",
      "Guaimaro|Guaimaro",
      "Gualandayes|Gualandayes",
      "Guanteros|Guanteros",
      "Hospital|Hospital",
      "Jardines|Jardines",
      "Jose Felix|Jose Felix",
      "La Abadia|La Abadia",
      "La Canalizacion|La Canalizacion",
      "La Casona|La Casona",
      "La Catedral|La Catedral",
      "La Cuadrita|La Cuadrita",
      "La Fe|La Fe",
      "La Frontera|La Frontera",
      "La Inmaculada|La Inmaculada",
      "La Intermedia|La Intermedia",
      "La Magnolia|La Magnolia",
      "La Mina|La Mina",
      "La Paloma|La Paloma",
      "La Paz|La Paz",
      "La Paz|La Paz",
      "La Pradera|La Pradera",
      "La Sebastiana|La Sebastiana",
      "Las Antillas|Las Antillas",
      "Las Brujas|Las Brujas",
      "Las Casitas|Las Casitas",
      "Las Cometas|Las Cometas",
      "Las Flores|Las Flores",
      "Las Flores|Las Flores",
      "Las Orquídeas|Las Orquídeas",
      "Las Vegas|Las Vegas",
      "Loma De Las Brujas|Loma De Las Brujas",
      "Loma Del Barro|Loma Del Barro",
      "Loma Del Campestre|Loma Del Campestre",
      "Loma Del Chocho|Loma Del Chocho",
      "Loma Del Escobero|Loma Del Escobero",
      "Loma El Atravezado|Loma El Atravezado",
      "Los Naranjos|Los Naranjos",
      "Mangazul|Mangazul",
      "Margaritas|Margaritas",
      "Mesa|Mesa",
      "Milán-vallejuelos|Milán-vallejuelos",
      "Montego|Montego",
      "Obrero|Obrero",
      "Otra Parte|Otra Parte",
      "Pio Xll|Pio Xll",
      "Pontevedra|Pontevedra",
      "Primavera|Primavera",
      "Rosellon|Rosellon",
      "San José|San José",
      "San Lucas|San Lucas",
      "San Mateo|San Mateo",
      "Santa Barbara|Santa Barbara",
      "Santa Gertrudis|Santa Gertrudis",
      "Señorial|Señorial",
      "Uribe Ángel|Uribe Ángel",
      "Villagrande|Villagrande",
      "Vistalegre|Vistalegre",
      "Zona Centro|Zona Centro",
      "Zuñiga|Zuñiga",
      "Zuñiga Alto|Zuñiga Alto"];

  } else if (colonia.value == "Fredonia") {
    var optionArray = ["|",
      "Vereda Piedra Verde|Vereda Piedra Verde"];

  } else if (colonia.value == "Girardota") {
    var optionArray = ["|",
      "Juan 23|Juan 23"];

  } else if (colonia.value == "Gomez Plata") {
    var optionArray = ["|",
      "Vereda Caney|Vereda Caney"];

  } else if (colonia.value == "Guarne") {
    var optionArray = ["|",
      "La Hondita|La Hondita",
      "San Antonio|San Antonio"];

  } else if (colonia.value == "Itagui") {
    var optionArray = ["|",
      "19 De Abril|19 De Abril",
      "Araucaria|Araucaria",
      "Artex|Artex",
      "Asturias|Asturias",
      "Balcones De Sevilla|Balcones De Sevilla",
      "Calatrava|Calatrava",
      "Camparola|Camparola",
      "Central Mayorista|Central Mayorista",
      "Centro|Centro",
      "Centro Itagui|Centro Itagui",
      "Colinas Del Sur|Colinas Del Sur",
      "Ditaires|Ditaires",
      "El Guayabo|El Guayabo",
      "El Palmar|El Palmar",
      "El Rosario|El Rosario",
      "El Tablazo|El Tablazo",
      "Fatima|Fatima",
      "Ferrara|Ferrara",
      "Glorieta Pilsen|Glorieta Pilsen",
      "Itagui|Itagui",
      "Itagui Parque Principal|Itagui Parque Principal",
      "Jardines Montesacro|Jardines Montesacro",
      "La Aldea|La Aldea",
      "La Finca|La Finca",
      "La Gloria|La Gloria",
      "La Independencia|La Independencia",
      "La Palama|La Palama",
      "La Raya|La Raya",
      "La Santa Cruz|La Santa Cruz",
      "La Union|La Union",
      "Las Acacias|Las Acacias",
      "Las Americas|Las Americas",
      "Las Asturias|Las Asturias",
      "Las Brisas|Las Brisas",
      "Las Margaritas|Las Margaritas",
      "Las Mercedes</option|Las Mercedes",
      "Loma Linda|Loma Linda",
      "Los Naranjos|Los Naranjos",
      "Malta|Malta",
      "Monte Verde|Monte Verde",
      "Pilsen|Pilsen",
      "Playa Rica|Playa Rica",
      "Samaria|Samaria",
      "Samaria N0 3|Samaria N0 3",
      "Samaria Nº1|Samaria Nº1",
      "San Antonio|San Antonio",
      "San Fernando|San Fernando",
      "San Francisco|San Francisco",
      "San Gabriel|San Gabriel",
      "San Isidro|San Isidro",
      "San Javier|San Javier",
      "San Jose|San Jose",
      "San Jose|San Jose",
      "San Juan Bautista|San Juan Bautista",
      "San Pio X|San Pio X",
      "San Pio X|San Pio X",
      "Santa Ana|Santa Ana",
      "Santa Catalina|Santa Catalina",
      "Santa Maria|Santa Maria",
      "Santa Maria La Nueva|Santa Maria La Nueva",
      "Santa Maria La Nueva|Santa Maria La Nueva",
      "Santa Maria Nº 1|Santa Maria Nº 1",
      "Santa Maria Nº 2|Santa Maria Nº 2",
      "Santa Maria Nº 3|Santa Maria Nº 3",
      "Satexco|Satexco",
      "Simon Bolivar|Simon Bolivar",
      "Simon Bolivar|Simon Bolivar",
      "Suramerica|Suramerica",
      "Terranova|Terranova",
      "Triana|Triana",
      "Vereda El Cano Mpio De Caldas|Vereda El Cano Mpio De Caldas",
      "Villa Paula|Villa Paula",
      "VIVIENDAS DEL SUR|VIVIENDAS DEL SUR",
      "Yarumito|Yarumito",
      "Yarumito|Yarumito",
      "Zona Industrial Nº1|Zona Industrial Nº1",
      "Zona Industrial Nº2|Zona Industrial Nº2",
      "Zona Industrial Nº3|Zona Industrial Nº3"];

  } else if (colonia.value == "La Estrella") {
    var optionArray = ["|",
      "La Estrella|La Estrella"];

  } else if (colonia.value == "Medellin") {
    var optionArray = ["|",
      "Aguacatala|Aguacatala",
      "Alfonso Lopez|Alfonso Lopez",
      "Almeria|Almeria",
      "America|America",
      "Aranjuez|Aranjuez",
      "Av Oriental / Sucre|Av Oriental / Sucre",
      "Barrio Cristobal|Barrio Cristobal",
      "Belen|Belen",
      "Belen Alameda|Belen Alameda",
      "Belen Fatima|Belen Fatima",
      "Belen Granada|Belen Granada",
      "Belen La Nubia|Belen La Nubia",
      "Belen La Palma|Belen La Palma",
      "Belen Las Playas|Belen Las Playas",
      "Belen Los Alpes|Belen Los Alpes",
      "Belen Los Alpes|Belen Los Alpes",
      "Belen Malibu|Belen Malibu",
      "Belen Rincon|Belen Rincon",
      "Belen Rosales|Belen Rosales",
      "Belen San Bernardo|Belen San Bernardo",
      "Bolivariana|Bolivariana",
      "Boston|Boston",
      "Buenos Aires|Buenos Aires",
      "Calasanz|Calasanz",
      "Calazania|Calazania",
      "Calle Colombia|Calle Colombia",
      "Campo Valdes|Campo Valdes",
      "Carlos C Restrepo|Carlos C Restrepo",
      "Castellana|Castellana",
      "Castilla|Castilla",
      "Centro|Centro",
      "Conquistadores|Conquistadores",
      "Cordoba|Cordoba",
      "Cristo Rey|Cristo Rey",
      "El Cortijon|El Cortijon",
      "El Pinal|El Pinal",
      "El Salvador|El Salvador",
      "Estadio|Estadio",
      "Florencia|Florencia",
      "Floresta|Floresta",
      "Florida Blanca|Florida Blanca",
      "Florida Nueva|Florida Nueva",
      "Guayabal|Guayabal",
      "Jesus Nazareno|Jesus Nazareno",
      "La Mota|La Mota",
      "La Playa|La Playa",
      "Las Palmas|Las Palmas",
      "Laureles|Laureles",
      "Loma De Los Bernal|Loma De Los Bernal",
      "Lopez De Mesa|Lopez De Mesa",
      "Los Angeles|Los Angeles",
      "Los Colores|Los Colores",
      "Lucia la Santa|Lucia la Santa",
      "Manrique|Manrique",
      "Manzanares|Manzanares",
      "Mayorca|Mayorca",
      "Milagrosa|Milagrosa",
      "Naranjal|Naranjal",
      "Nueva Villa Del Aburra|Nueva Villa Del Aburra",
      "Parque Berrio|Parque Berrio",
      "Parque Bolivar|Parque Bolivar",
      "Pedregal|Pedregal",
      "Pilarica|Pilarica",
      "Plaza Flores|Plaza Flores",
      "Poblado|Poblado",
      "Prado Centro|Prado Centro",
      "Ratón pelado|Ratón pelado",
      "Robledo|Robledo",
      "Robledo Kennedy|Robledo Kennedy",
      "Robledo La Pola|Robledo La Pola",
      "Rodeo|Rodeo",
      "San Antonio De Prado|San Antonio De Prado",
      "San Cristobal|San Cristobal",
      "San Diego|San Diego",
      "San Javier|San Javier",
      "San Joaquin|San Joaquin",
      "San Joselito|San Joselito",
      "San Juan|San Juan",
      "San Pablo|San Pablo",
      "Santa Fe|Santa Fe",
      "Santa Lucia|Santa Lucia",
      "Santa Monica|Santa Monica",
      "Sevilla|Sevilla",
      "Simon Bolivar|Simon Bolivar",
      "Suramericana|Suramericana",
      "Tricentenario|Tricentenario",
      "Trinidad|Trinidad",
      "Velodromo|Velodromo",
      "Vereda La Verde|Vereda La Verde",
      "Villa De La Aburra|Villa De La Aburra",
      "Villa Hermosa|Villa Hermosa"];

  } else if (colonia.value == "Sabaneta") {
    var optionArray = ["|",
      "Aliadas|Aliadas",
      "Aves Maria|Aves Maria",
      "Aves Marias|Aves Marias",
      "Betania|Betania",
      "Calle Del Banco|Calle Del Banco",
      "Calle Larga|Calle Larga",
      "Ces|Ces",
      "El Carmelo|El Carmelo",
      "El Embarcadero|El Embarcadero",
      "Entregamigos|Entregamigos",
      "Gravetal|Gravetal",
      "Holanda|Holanda",
      "La Florida|La Florida",
      "Manuel Restrepo|Manuel Restrepo",
      "María Auxiliadora|María Auxiliadora",
      "Metropolitano|Metropolitano",
      "Paso Ancho|Paso Ancho",
      "Playas De María|Playas De María",
      "Prados De Sabaneta|Prados De Sabaneta",
      "Restrepo Narango|Restrepo Narango",
      "Sabaneta|Sabaneta",
      "San Joaquin|San Joaquin",
      "Santa Ana|Santa Ana",
      "Tres Esquinas|Tres Esquinas",
      "Villas Del Carmen|Villas Del Carmen",
      "Virgen Del Carmen|Virgen Del Carmen"];

  } else if (colonia.value == "Santa Rosa De Osos") {
    var optionArray = ["|",
      "Vereda Pontezuela|Vereda Pontezuela"];

  } else if (colonia.value == "Barranquilla") {
    var optionArray = ["|",
      "Altoprado|Altoprado",
      "LAS DELICIAS|LAS DELICIAS"];

  } else if (colonia.value == "Bogota") {
    var optionArray = ["|",
      "Cedritos|Cedritos",
      "Chapinero|Chapinero"];

  } else if (colonia.value == "Cartagena") {
    var optionArray = ["|",
      "13 De Junio|13 De Junio",
      "Alameda La Victoria|Alameda La Victoria",
      "Albornoz|Albornoz",
      "Alcibia|Alcibia",
      "Almirante Colon|Almirante Colon",
      "Alto Bosque|Alto Bosque",
      "Altos De San Isidro|Altos De San Isidro",
      "Altos Del Campestre|Altos Del Campestre",
      "Altos Del Nuevo Bosque|Altos Del Nuevo Bosque",
      "Altos Los Jardines|Altos Los Jardines",
      "Amberes|Amberes",
      "Andalucia|Andalucia",
      "Anillo Vial|Anillo Vial",
      "Arjona|Arjona",
      "Armenia|Armenia",
      "Barcelona De Indias|Barcelona De Indias",
      "Barrio Chino|Barrio Chino",
      "Baru|Baru",
      "Bayunca|Bayunca",
      "Bellavista|Bellavista",
      "Blas De Lezo|Blas De Lezo",
      "Bocagrande|Bocagrande",
      "Bosque|Bosque",
      "Bosquecito|Bosquecito",
      "Bosques De La Circunvalar|Bosques De La Circunvalar",
      "Boston|Boston",
      "Bruselas|Bruselas",
      "Buenos Aires|Buenos Aires",
      "Camino Del Medio|Camino Del Medio",
      "Canapote|Canapote",
      "Caño Del Oro|Caño Del Oro",
      "Castillete|Castillete",
      "Castillogrande|Castillogrande",
      "Ceballos|Ceballos",
      "Centro|Centro",
      "Cerro La Popa|Cerro La Popa",
      "Chambacu|Chambacu",
      "Chapacua|Chapacua",
      "Chipre|Chipre",
      "Chiquinquira|Chiquinquira",
      "Cielo Mar|Cielo Mar",
      "Ciudadela 2000|Ciudadela 2000",
      "Conjunto Residencial Quintas De Alta Lucia|Conjunto Residencial Quintas De Alta Lucia",
      "Contadora|Contadora",
      "Crespito|Crespito",
      "Crespo|Crespo",
      "Daniel Lemaitre|Daniel Lemaitre",
      "El Bosque|El Bosque",
      "El Cabrero|El Cabrero",
      "El Campestre|El Campestre",
      "El Carmelo|El Carmelo",
      "El Carmen|El Carmen",
      "El Contry|El Contry",
      "El Eden|El Eden",
      "El Educador|El Educador",
      "El Espinal|El Espinal",
      "El Gallo|El Gallo",
      "El Golf|El Golf",
      "El Laguito|El Laguito",
      "El Libano|El Libano",
      "El Libertador|El Libertador",
      "El Milagro|El Milagro",
      "El Paraiso|El Paraiso",
      "El Porvenir|El Porvenir",
      "El Pozon|El Pozon",
      "El Prado|El Prado",
      "El Progreso|El Progreso",
      "El Pueblito|El Pueblito",
      "El Recreo|El Recreo",
      "El Reposo|El Reposo",
      "El Rodeo|El Rodeo",
      "El Rubi|El Rubi",
      "El Silencio|El Silencio",
      "El Socorro|El Socorro",
      "Escallon Villa|Escallon Villa",
      "España|España",
      "Fredonia|Fredonia",
      "Getsemani|Getsemani",
      "Granada|Granada",
      "Isla De Manzanillo|Isla De Manzanillo",
      "Jardines De Junio|Jardines De Junio",
      "Jorge Eliecer Gaitan|Jorge Eliecer Gaitan",
      "Jose Antonio Galan|Jose Antonio Galan",
      "Juan Xxiii|Juan Xxiii",
      "Junin|Junin",
      "La Bonguita|La Bonguita",
      "La Boquilla|La Boquilla",
      "La Campiña|La Campiña",
      "La Candelaria|La Candelaria",
      "La Carolina|La Carolina",
      "La Castellana|La Castellana",
      "La Central|La Central",
      "La Concepcion|La Concepcion",
      "La Conquista|La Conquista",
      "La Consolata|La Consolata",
      "La Esperanza|La Esperanza",
      "La Floresta|La Floresta",
      "La Maria|La Maria",
      "La Matuna|La Matuna",
      "La Plazuela|La Plazuela",
      "La Princesa|La Princesa",
      "La Providencia|La Providencia",
      "La Quinta|La Quinta",
      "La Reina|La Reina",
      "La Sierrita|La Sierrita",
      "La Troncal|La Troncal",
      "La Victoria|La Victoria",
      "La Villa|La Villa",
      "Las Delicias|Las Delicias",
      "Las Gavias|Las Gavias",
      "Las Gaviotas|Las Gaviotas",
      "Las Lomas|Las Lomas",
      "Las Palmeras|Las Palmeras",
      "Leticia|Leticia",
      "Lo Amador|Lo Amador",
      "Loma Fresca|Loma Fresca",
      "Los Alpes|Los Alpes",
      "Los Angeles|Los Angeles",
      "Los Calamares|Los Calamares",
      "Los Caracoles|Los Caracoles",
      "Los Cerezos|Los Cerezos",
      "Los Cerros|Los Cerros",
      "Los Ciruelos|Los Ciruelos",
      "Los Corales|Los Corales",
      "Los Ejecutivos|Los Ejecutivos",
      "Los Jardines|Los Jardines",
      "Luis Carlos Galan|Luis Carlos Galan",
      "Mamonal|Mamonal",
      "Manga|Manga",
      "Manzanares|Manzanares",
      "Manzanillo Del Mar|Manzanillo Del Mar",
      "Marbella|Marbella",
      "Maria Auxiliadora|Maria Auxiliadora",
      "Maria Cano|Maria Cano",
      "Martinez Martelo|Martinez Martelo",
      "Medellin|Medellin",
      "Membrillal|Membrillal",
      "Mirador Del Nuevo Bosque|Mirador Del Nuevo Bosque",
      "Monserrate|Monserrate",
      "Nariño|Nariño",
      "Navas Meisel|Navas Meisel",
      "Nazareno|Nazareno",
      "Nelson Mandela|Nelson Mandela",
      "Nueva Granada|Nueva Granada",
      "Nueva Venecia|Nueva Venecia",
      "Nuevo Bosque|Nuevo Bosque",
      "Nuevo Campestre|Nuevo Campestre",
      "Nuevo Chile|Nuevo Chile",
      "Nuevo Paraguay|Nuevo Paraguay",
      "Nuevo Paraiso|Nuevo Paraiso",
      "Nuevo Porvenir|Nuevo Porvenir",
      "Nuevos Jardines|Nuevos Jardines",
      "Olaya Herrera|Olaya Herrera",
      "Pablo Vi|Pablo Vi",
      "Palestina|Palestina",
      "Pantano De Vargas|Pantano De Vargas",
      "Paraguay|Paraguay",
      "Pasacaballos|Pasacaballos",
      "Paseo Bolivar|Paseo Bolivar",
      "Pedro Salazar|Pedro Salazar",
      "Petares|Petares",
      "Pie De La Popa|Pie De La Popa",
      "Pie Del Cerro|Pie Del Cerro",
      "Piedra De Bolivar|Piedra De Bolivar",
      "Policarpa|Policarpa",
      "Pontezuela|Pontezuela",
      "Providencia|Providencia",
      "Puerta De Hierro|Puerta De Hierro",
      "Puerto Rey|Puerto Rey",
      "Punta Arena|Punta Arena",
      "Punta Canoa|Punta Canoa",
      "Quindio|Quindio",
      "Republica De Chile|Republica De Chile",
      "Republica De Venezuela|Republica De Venezuela",
      "Republica Del Caribe|Republica Del Caribe",
      "Rosario|Rosario",
      "San Antonio|San Antonio",
      "San Diego|San Diego",
      "San Fernando|San Fernando",
      "San Francisco|San Francisco",
      "San Isidro|San Isidro",
      "San Jose De Los Campanos|San Jose De Los Campanos",
      "San Pedro|San Pedro",
      "San Pedro Martir|San Pedro Martir",
      "San Vicente De Paul|San Vicente De Paul",
      "Santa Ana|Santa Ana",
      "Santa Clara|Santa Clara",
      "Santa Lucia|Santa Lucia",
      "Santa Maria|Santa Maria",
      "Santa Monica|Santa Monica",
      "Santa Rita|Santa Rita",
      "Sec. Unidos - Nuevo Jerusalen|Sec. Unidos - Nuevo Jerusalen",
      "Sectores Unidos|Sectores Unidos",
      "Simon Bolivar|Simon Bolivar",
      "Tacarigua|Tacarigua",
      "Ternera|Ternera",
      "Terranova|Terranova",
      "Tesca Nuevo|Tesca Nuevo",
      "Tierra Baja|Tierra Baja",
      "Tierrabomba|Tierrabomba",
      "Torices|Torices",
      "Turbaco|Turbaco",
      "Turbana|Turbana",
      "Urb Barlovento|Urb Barlovento",
      "Urb Luis Carlos Galan|Urb Luis Carlos Galan",
      "Urb Puerta De Los Alpes|Urb Puerta De Los Alpes",
      "Urb. Flor Del Campo|Urb. Flor Del Campo",
      "Urbanizacion Anita|Urbanizacion Anita",
      "Urbanizacion Camaguey|Urbanizacion Camaguey",
      "Villa Corelca|Villa Corelca",
      "Villa Country|Villa Country",
      "Villa Estrella|Villa Estrella",
      "Villa Fanny|Villa Fanny",
      "Villa Hermosa|Villa Hermosa",
      "Villa Margarita|Villa Margarita",
      "Villa Rosita|Villa Rosita",
      "Villa Sandra|Villa Sandra",
      "Vista Hermosa|Vista Hermosa",
      "Zaragocilla|Zaragocilla"];

  } else if (colonia.value == "Valledupar") {
    var optionArray = ["|",
      "20 De Julio|20 De Julio",
      "5 De Enero|5 De Enero",
      "Álamos Ii|Álamos Ii",
      "Álamos Iii|Álamos Iii",
      "Alfonso López|Alfonso López",
      "Altagracia|Altagracia",
      "Altos De Zaruma|Altos De Zaruma",
      "Altos Del Rosario|Altos Del Rosario",
      "Altos Del Rosario|Altos Del Rosario",
      "Amaneceres Del Valle|Amaneceres Del Valle",
      "Aremasain|Aremasain",
      "Arizona|Arizona",
      "Atlantis|Atlantis",
      "Azúcar Buena|Azúcar Buena",
      "Bella Vista|Bella Vista",
      "Bello Horizonte|Bello Horizonte",
      "Buena Vista|Buena Vista",
      "Campo Florido|Campo Florido",
      "Campo Romero|Campo Romero",
      "Cañaguate|Cañaguate",
      "Candelaria Norte|Candelaria Norte",
      "Candelaria Sur|Candelaria Sur",
      "Canta Rana|Canta Rana",
      "Casa Blanca|Casa Blanca",
      "Casimiro Maestre|Casimiro Maestre",
      "Centro|Centro",
      "Cerezo|Cerezo",
      "Chimila|Chimila",
      "Chiriquí|Chiriquí",
      "Cicerón Maestre|Cicerón Maestre",
      "Cinco De Noviembre|Cinco De Noviembre",
      "Ciudad Jardín|Ciudad Jardín",
      "Ciudadela 450 Años|Ciudadela 450 Años",
      "Ciudadela Comfacesar|Ciudadela Comfacesar",
      "Clemente Quintero|Clemente Quintero",
      "Concepción Pérez|Concepción Pérez",
      "Conjunto Cerrado  Los Rosales|Conjunto Cerrado  Los Rosales",
      "Conjunto Cerrado Balcones De Santa Elena|Conjunto Cerrado Balcones De Santa Elena",
      "Conjunto Cerrado La Fontana|Conjunto Cerrado La Fontana",
      "Conjunto Cerrado Los Cortijos|Conjunto Cerrado Los Cortijos",
      "Conjunto Cerrado Quintas  Del Rosario|Conjunto Cerrado Quintas  Del Rosario",
      "Conjunto Residencial Callejas|Conjunto Residencial Callejas",
      "Conjunto Residencial Del Norte|Conjunto Residencial Del Norte",
      "Conjunto Residencial Ogb|Conjunto Residencial Ogb",
      "Conjunto Residencial Rosas Del Ateneo|Conjunto Residencial Rosas Del Ateneo",
      "Conjunto Residencial San Pedro|Conjunto Residencial San Pedro",
      "Dangond|Dangond",
      "Divino Niño|Divino Niño",
      "Doce De Octubre|Doce De Octubre",
      "Don Carmelo|Don Carmelo",
      "Don Felipe|Don Felipe",
      "Don Lucas|Don Lucas",
      "Dos De Marzo|Dos De Marzo",
      "Dundakare|Dundakare",
      "Edgardo Pupo|Edgardo Pupo",
      "El Amparo|El Amparo",
      "El Carmen Kennedy|El Carmen Kennedy",
      "El Cerrito|El Cerrito",
      "El Edén Y|El Edén Y",
      "El Hogar|El Hogar",
      "El Mirador Del Valle|El Mirador Del Valle",
      "El Oasis|El Oasis",
      "El Páramo|El Páramo",
      "El Portal Del Cerrito|El Portal Del Cerrito",
      "El Portal Del Rosario|El Portal Del Rosario",
      "El Prado|El Prado",
      "El Progreso|El Progreso",
      "El Rincón Del Amparo|El Rincón Del Amparo",
      "Enrique Pupo|Enrique Pupo",
      "Esperanza Oriente|Esperanza Oriente",
      "Francisco De Paula Santander|Francisco De Paula Santander",
      "Francisco Javier|Francisco Javier",
      "Futuro De Los Niños|Futuro De Los Niños",
      "Gaitán|Gaitán",
      "Galán|Galán",
      "Garupal|Garupal",
      "Gerizim|Gerizim",
      "Girasoles|Girasoles",
      "Guajira|Guajira",
      "Guatapurí|Guatapurí",
      "Hernando De Santana|Hernando De Santana",
      "Ichagua|Ichagua",
      "Iracal|Iracal",
      "La Esperanza|La Esperanza",
      "La Felicidad|La Felicidad",
      "La Garita|La Garita",
      "La Granja|La Granja",
      "La Manuelita|La Manuelita",
      "La Nevada|La Nevada",
      "La Popa|La Popa",
      "La Victoria|La Victoria",
      "Las Acacias|Las Acacias",
      "Las Delicias|Las Delicias",
      "Las Flores|Las Flores",
      "Las Margaritas|Las Margaritas",
      "Las Palmas|Las Palmas",
      "Limonar|Limonar",
      "Loperena|Loperena",
      "Los Álamos|Los Álamos",
      "Los Ángeles|Los Ángeles",
      "Los Caciques|Los Caciques",
      "Los Cámpanos|Los Cámpanos",
      "Los Cocos|Los Cocos",
      "Los Corales|Los Corales",
      "Los Cortijos|Los Cortijos",
      "Los Fundadores|Los Fundadores",
      "Los Guasimales|Los Guasimales",
      "Los Milagros|Los Milagros",
      "Manantial|Manantial",
      "Mareigua|Mareigua",
      "María Valeria|María Valeria",
      "Maruámake|Maruámake",
      "Mayales|Mayales",
      "Novalito|Novalito",
      "Nueva Colombia|Nueva Colombia",
      "Nueva Esperanza|Nueva Esperanza",
      "Nuevo Amanecer|Nuevo Amanecer",
      "Obrero|Obrero",
      "Ocho  De Diciembre|Ocho  De Diciembre",
      "Once De Noviembre|Once De Noviembre",
      "Orientes De Calleja|Orientes De Calleja",
      "Pablo Vi|Pablo Vi",
      "Panamá|Panamá",
      "Paraíso|Paraíso",
      "Pasadera|Pasadera",
      "Pedro Nel Martínez|Pedro Nel Martínez",
      "Pescaito|Pescaito",
      "Pontevedra|Pontevedra",
      "Primero De Mayo|Primero De Mayo",
      "Quintas Del Country|Quintas Del Country",
      "Rincón De Zaruma|Rincón De Zaruma",
      "Rocas Del Valle|Rocas Del Valle",
      "Rosanía|Rosanía",
      "Rueda|Rueda",
      "Sabanas Del Valle|Sabanas Del Valle",
      "San Antonio|San Antonio",
      "San Carlos|San Carlos",
      "San Clemente|San Clemente",
      "San Fernando|San Fernando",
      "San Francisco|San Francisco",
      "San Isidro|San Isidro",
      "San Isidro|San Isidro",
      "San Jerónimo|San Jerónimo",
      "San Joaquín|San Joaquín",
      "San Jorge|San Jorge",
      "San Jorge|San Jorge",
      "San Marino|San Marino",
      "San Martín|San Martín",
      "San Pedro|San Pedro",
      "San Vicente|San Vicente",
      "Santa Rita|Santa Rita",
      "Santa Rosa|Santa Rosa",
      "Santa Rosa|Santa Rosa",
      "Santo Domingo|Santo Domingo",
      "Serranilla|Serranilla",
      "Sicarare|Sicarare",
      "Siete De Agosto|Siete De Agosto",
      "Simón Bolívar|Simón Bolívar",
      "Urb Altos De Comfacesar|Urb Altos De Comfacesar",
      "Urb Bosques De Rancho  Mío|Urb Bosques De Rancho  Mío",
      "Urb Casa E Campo|Urb Casa E Campo",
      "Urb Club House|Urb Club House",
      "Urb Galán Sarmiento|Urb Galán Sarmiento",
      "Urb La 27 Nuevo Milenio|Urb La 27 Nuevo Milenio",
      "Urb La Castellana|Urb La Castellana",
      "Urb La Floresta|Urb La Floresta",
      "Urb Lindaraja|Urb Lindaraja",
      "Urb María Camila|Urb María Camila",
      "Urb María Camila Norte|Urb María Camila Norte",
      "Urb María Elena|Urb María Elena",
      "Urb Mayales Aeropuerto|Urb Mayales Aeropuerto",
      "Urb Mayales I Ii Iii|Urb Mayales I Ii Iii",
      "Urb Populandia|Urb Populandia",
      "Urb Rincón  Del Villalba|Urb Rincón  Del Villalba",
      "Urb San Fernando|Urb San Fernando",
      "Urb Santa Rosalía|Urb Santa Rosalía",
      "Urb Santo Tomás|Urb Santo Tomás",
      "Urb Valle Hermoso|Urb Valle Hermoso",
      "Urbanización Altagracia|Urbanización Altagracia",
      "Urbanización Ceiba Alta Gracia|Urbanización Ceiba Alta Gracia",
      "Urbanización Ciudad Tayrona|Urbanización Ciudad Tayrona",
      "Urbanización Ciudad Tayrona Ii|Urbanización Ciudad Tayrona Ii",
      "Urbanización Don Alberto|Urbanización Don Alberto",
      "Urbanización El Refugio|Urbanización El Refugio",
      "Urbanización Francisco El Hombre|Urbanización Francisco El Hombre",
      "Urbanización La Ceiba|Urbanización La Ceiba",
      "Urbanización María Raiza|Urbanización María Raiza",
      "Urbanización Panamá|Urbanización Panamá",
      "Urbanización Rosario Norte|Urbanización Rosario Norte",
      "Urbanización Tobías Daza|Urbanización Tobías Daza",
      "Valle Meza|Valle Meza",
      "Veinticinco  De Diciembre|Veinticinco  De Diciembre",
      "Versalles|Versalles",
      "Villa  Algenia|Villa  Algenia",
      "Villa Andrés|Villa Andrés",
      "Villa Carel|Villa Carel",
      "Villa Carolina|Villa Carolina",
      "Villa Castro|Villa Castro",
      "Villa Clara|Villa Clara",
      "Villa Concha|Villa Concha",
      "Villa Consuelo|Villa Consuelo",
      "Villa Corelca|Villa Corelca",
      "Villa Dariana|Villa Dariana",
      "Villa Del Rosario|Villa Del Rosario",
      "Villa Del Rosario Norte|Villa Del Rosario Norte",
      "Villa Estefanía|Villa Estefanía",
      "Villa Fanny|Villa Fanny",
      "Villa Fuentes|Villa Fuentes",
      "Villa Haidith|Villa Haidith",
      "Villa Leonor|Villa Leonor",
      "Villa Ligia I|Villa Ligia I",
      "Villa Ligia Ii|Villa Ligia Ii",
      "Villa Ligia Iii|Villa Ligia Iii",
      "Villa Luz|Villa Luz",
      "Villa Magdala|Villa Magdala",
      "Villa Miriam|Villa Miriam",
      "Villa Mónica|Villa Mónica",
      "Villa Olga|Villa Olga",
      "Villa Taxi|Villa Taxi",
      "Villa Vanesa|Villa Vanesa",
      "Villa Yaneth|Villa Yaneth",
      "Villa Yaneth|Villa Yaneth",
      "Villalba|Villalba",
      "Zapato En Mano|Zapato En Mano"];

  } else if (colonia.value == "Monteria") {
    var optionArray = ["|",
      "Angeles|Angeles",
      "Brizalia|Brizalia",
      "Buenavista|Buenavista",
      "Caracoli|Caracoli",
      "Castellana|Castellana",
      "Castilla La Nueva|Castilla La Nueva",
      "Centro|Centro",
      "Colon|Colon",
      "El Amparo|El Amparo",
      "El Eden|El Eden",
      "Elamparo|Elamparo",
      "Floresta|Floresta",
      "Juan Xiii|Juan Xiii",
      "Julia|Julia",
      "La Granja|La Granja",
      "Lacharme|Lacharme",
      "Los Alcazares|Los Alcazares",
      "Los Angeles|Los Angeles",
      "Mocari|Mocari",
      "Monteverde|Monteverde",
      "Pasatiempo|Pasatiempo",
      "Portal De Alamedas|Portal De Alamedas",
      "Portal De Almeria|Portal De Almeria",
      "Pradera|Pradera",
      "Recreo|Recreo",
      "Republica De Panama|Republica De Panama",
      "Samaria Ii|Samaria Ii",
      "Sucre|Sucre",
      "Urb. San Francisco|Urb. San Francisco",
      "Urb. Santa Helena|Urb. Santa Helena",
      "Urbina|Urbina",
      "Versalles|Versalles",
      "Villa Del Rio|Villa Del Rio",
      "Villa Jardin|Villa Jardin",
      "Villa Nueva|Villa Nueva",
      "Villa Real|Villa Real"];

  } else if (colonia.value == "Cajica") {
    var optionArray = ["|",
      "La Estacion|La Estacion"];

  } else if (colonia.value == "Fusagasuga") {
    var optionArray = ["|",
      "Balmoral|Balmoral"];

  } else if (colonia.value == "Neiva") {
    var optionArray = ["|",
      "Chigororo|Chigororo"];

  } else if (colonia.value == "Acacias") {
    var optionArray = ["|",
      "Los Laureles|Los Laureles",
      "San Francisco|San Francisco"];

  };




  for (option = 0; option < optionArray.length; option++) {
    var pair = optionArray[option].split("|");
    var newOption = document.createElement("option");
    newOption.value = pair[0];
    newOption.innerHTML = pair[1];
    letra.options.add(newOption);
  };

}
